// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package ma.enset.stub;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    java.lang.String getCurrentFrom();
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    com.google.protobuf.ByteString
        getCurrentFromBytes();

    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    java.lang.String getCurrentTo();
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    com.google.protobuf.ByteString
        getCurrentToBytes();

    /**
     * <code>string currentMsg = 3;</code>
     * @return The currentMsg.
     */
    java.lang.String getCurrentMsg();
    /**
     * <code>string currentMsg = 3;</code>
     * @return The bytes for currentMsg.
     */
    com.google.protobuf.ByteString
        getCurrentMsgBytes();
  }
  /**
   * Protobuf type {@code MessageRequest}
   */
  public  static final class MessageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageRequest)
      MessageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageRequest.newBuilder() to construct.
    private MessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageRequest() {
      currentFrom_ = "";
      currentTo_ = "";
      currentMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currentFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currentTo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              currentMsg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.enset.stub.Chat.internal_static_MessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.enset.stub.Chat.internal_static_MessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.enset.stub.Chat.MessageRequest.class, ma.enset.stub.Chat.MessageRequest.Builder.class);
    }

    public static final int CURRENTFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentFrom_;
    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    public java.lang.String getCurrentFrom() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    public com.google.protobuf.ByteString
        getCurrentFromBytes() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currentTo_;
    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    public java.lang.String getCurrentTo() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    public com.google.protobuf.ByteString
        getCurrentToBytes() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object currentMsg_;
    /**
     * <code>string currentMsg = 3;</code>
     * @return The currentMsg.
     */
    public java.lang.String getCurrentMsg() {
      java.lang.Object ref = currentMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string currentMsg = 3;</code>
     * @return The bytes for currentMsg.
     */
    public com.google.protobuf.ByteString
        getCurrentMsgBytes() {
      java.lang.Object ref = currentMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrentFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currentTo_);
      }
      if (!getCurrentMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, currentMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrentFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currentTo_);
      }
      if (!getCurrentMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, currentMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.enset.stub.Chat.MessageRequest)) {
        return super.equals(obj);
      }
      ma.enset.stub.Chat.MessageRequest other = (ma.enset.stub.Chat.MessageRequest) obj;

      if (!getCurrentFrom()
          .equals(other.getCurrentFrom())) return false;
      if (!getCurrentTo()
          .equals(other.getCurrentTo())) return false;
      if (!getCurrentMsg()
          .equals(other.getCurrentMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentFrom().hashCode();
      hash = (37 * hash) + CURRENTTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTo().hashCode();
      hash = (37 * hash) + CURRENTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.enset.stub.Chat.MessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.stub.Chat.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.enset.stub.Chat.MessageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageRequest)
        ma.enset.stub.Chat.MessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.enset.stub.Chat.internal_static_MessageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.enset.stub.Chat.internal_static_MessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.enset.stub.Chat.MessageRequest.class, ma.enset.stub.Chat.MessageRequest.Builder.class);
      }

      // Construct using ma.enset.stub.Chat.MessageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentFrom_ = "";

        currentTo_ = "";

        currentMsg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.enset.stub.Chat.internal_static_MessageRequest_descriptor;
      }

      @java.lang.Override
      public ma.enset.stub.Chat.MessageRequest getDefaultInstanceForType() {
        return ma.enset.stub.Chat.MessageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ma.enset.stub.Chat.MessageRequest build() {
        ma.enset.stub.Chat.MessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.enset.stub.Chat.MessageRequest buildPartial() {
        ma.enset.stub.Chat.MessageRequest result = new ma.enset.stub.Chat.MessageRequest(this);
        result.currentFrom_ = currentFrom_;
        result.currentTo_ = currentTo_;
        result.currentMsg_ = currentMsg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.enset.stub.Chat.MessageRequest) {
          return mergeFrom((ma.enset.stub.Chat.MessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.enset.stub.Chat.MessageRequest other) {
        if (other == ma.enset.stub.Chat.MessageRequest.getDefaultInstance()) return this;
        if (!other.getCurrentFrom().isEmpty()) {
          currentFrom_ = other.currentFrom_;
          onChanged();
        }
        if (!other.getCurrentTo().isEmpty()) {
          currentTo_ = other.currentTo_;
          onChanged();
        }
        if (!other.getCurrentMsg().isEmpty()) {
          currentMsg_ = other.currentMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.enset.stub.Chat.MessageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.enset.stub.Chat.MessageRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currentFrom_ = "";
      /**
       * <code>string currentFrom = 1;</code>
       * @return The currentFrom.
       */
      public java.lang.String getCurrentFrom() {
        java.lang.Object ref = currentFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return The bytes for currentFrom.
       */
      public com.google.protobuf.ByteString
          getCurrentFromBytes() {
        java.lang.Object ref = currentFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentFrom() {
        
        currentFrom_ = getDefaultInstance().getCurrentFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The bytes for currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currentTo_ = "";
      /**
       * <code>string currentTo = 2;</code>
       * @return The currentTo.
       */
      public java.lang.String getCurrentTo() {
        java.lang.Object ref = currentTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return The bytes for currentTo.
       */
      public com.google.protobuf.ByteString
          getCurrentToBytes() {
        java.lang.Object ref = currentTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTo() {
        
        currentTo_ = getDefaultInstance().getCurrentTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The bytes for currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentTo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currentMsg_ = "";
      /**
       * <code>string currentMsg = 3;</code>
       * @return The currentMsg.
       */
      public java.lang.String getCurrentMsg() {
        java.lang.Object ref = currentMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @return The bytes for currentMsg.
       */
      public com.google.protobuf.ByteString
          getCurrentMsgBytes() {
        java.lang.Object ref = currentMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @param value The currentMsg to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentMsg() {
        
        currentMsg_ = getDefaultInstance().getCurrentMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @param value The bytes for currentMsg to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageRequest)
    }

    // @@protoc_insertion_point(class_scope:MessageRequest)
    private static final ma.enset.stub.Chat.MessageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.enset.stub.Chat.MessageRequest();
    }

    public static ma.enset.stub.Chat.MessageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageRequest>
        PARSER = new com.google.protobuf.AbstractParser<MessageRequest>() {
      @java.lang.Override
      public MessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.enset.stub.Chat.MessageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageRespenseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageRespense)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    java.lang.String getCurrentFrom();
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    com.google.protobuf.ByteString
        getCurrentFromBytes();

    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    java.lang.String getCurrentTo();
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    com.google.protobuf.ByteString
        getCurrentToBytes();

    /**
     * <code>string currentMsg = 3;</code>
     * @return The currentMsg.
     */
    java.lang.String getCurrentMsg();
    /**
     * <code>string currentMsg = 3;</code>
     * @return The bytes for currentMsg.
     */
    com.google.protobuf.ByteString
        getCurrentMsgBytes();
  }
  /**
   * Protobuf type {@code MessageRespense}
   */
  public  static final class MessageRespense extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageRespense)
      MessageRespenseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageRespense.newBuilder() to construct.
    private MessageRespense(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageRespense() {
      currentFrom_ = "";
      currentTo_ = "";
      currentMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageRespense();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageRespense(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currentFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currentTo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              currentMsg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.enset.stub.Chat.internal_static_MessageRespense_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.enset.stub.Chat.internal_static_MessageRespense_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.enset.stub.Chat.MessageRespense.class, ma.enset.stub.Chat.MessageRespense.Builder.class);
    }

    public static final int CURRENTFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentFrom_;
    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    public java.lang.String getCurrentFrom() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    public com.google.protobuf.ByteString
        getCurrentFromBytes() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currentTo_;
    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    public java.lang.String getCurrentTo() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    public com.google.protobuf.ByteString
        getCurrentToBytes() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object currentMsg_;
    /**
     * <code>string currentMsg = 3;</code>
     * @return The currentMsg.
     */
    public java.lang.String getCurrentMsg() {
      java.lang.Object ref = currentMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string currentMsg = 3;</code>
     * @return The bytes for currentMsg.
     */
    public com.google.protobuf.ByteString
        getCurrentMsgBytes() {
      java.lang.Object ref = currentMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrentFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currentTo_);
      }
      if (!getCurrentMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, currentMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrentFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currentTo_);
      }
      if (!getCurrentMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, currentMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.enset.stub.Chat.MessageRespense)) {
        return super.equals(obj);
      }
      ma.enset.stub.Chat.MessageRespense other = (ma.enset.stub.Chat.MessageRespense) obj;

      if (!getCurrentFrom()
          .equals(other.getCurrentFrom())) return false;
      if (!getCurrentTo()
          .equals(other.getCurrentTo())) return false;
      if (!getCurrentMsg()
          .equals(other.getCurrentMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentFrom().hashCode();
      hash = (37 * hash) + CURRENTTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTo().hashCode();
      hash = (37 * hash) + CURRENTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRespense parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.enset.stub.Chat.MessageRespense parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.stub.Chat.MessageRespense parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.enset.stub.Chat.MessageRespense prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageRespense}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageRespense)
        ma.enset.stub.Chat.MessageRespenseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.enset.stub.Chat.internal_static_MessageRespense_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.enset.stub.Chat.internal_static_MessageRespense_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.enset.stub.Chat.MessageRespense.class, ma.enset.stub.Chat.MessageRespense.Builder.class);
      }

      // Construct using ma.enset.stub.Chat.MessageRespense.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentFrom_ = "";

        currentTo_ = "";

        currentMsg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.enset.stub.Chat.internal_static_MessageRespense_descriptor;
      }

      @java.lang.Override
      public ma.enset.stub.Chat.MessageRespense getDefaultInstanceForType() {
        return ma.enset.stub.Chat.MessageRespense.getDefaultInstance();
      }

      @java.lang.Override
      public ma.enset.stub.Chat.MessageRespense build() {
        ma.enset.stub.Chat.MessageRespense result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.enset.stub.Chat.MessageRespense buildPartial() {
        ma.enset.stub.Chat.MessageRespense result = new ma.enset.stub.Chat.MessageRespense(this);
        result.currentFrom_ = currentFrom_;
        result.currentTo_ = currentTo_;
        result.currentMsg_ = currentMsg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.enset.stub.Chat.MessageRespense) {
          return mergeFrom((ma.enset.stub.Chat.MessageRespense)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.enset.stub.Chat.MessageRespense other) {
        if (other == ma.enset.stub.Chat.MessageRespense.getDefaultInstance()) return this;
        if (!other.getCurrentFrom().isEmpty()) {
          currentFrom_ = other.currentFrom_;
          onChanged();
        }
        if (!other.getCurrentTo().isEmpty()) {
          currentTo_ = other.currentTo_;
          onChanged();
        }
        if (!other.getCurrentMsg().isEmpty()) {
          currentMsg_ = other.currentMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.enset.stub.Chat.MessageRespense parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.enset.stub.Chat.MessageRespense) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currentFrom_ = "";
      /**
       * <code>string currentFrom = 1;</code>
       * @return The currentFrom.
       */
      public java.lang.String getCurrentFrom() {
        java.lang.Object ref = currentFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return The bytes for currentFrom.
       */
      public com.google.protobuf.ByteString
          getCurrentFromBytes() {
        java.lang.Object ref = currentFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentFrom() {
        
        currentFrom_ = getDefaultInstance().getCurrentFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The bytes for currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currentTo_ = "";
      /**
       * <code>string currentTo = 2;</code>
       * @return The currentTo.
       */
      public java.lang.String getCurrentTo() {
        java.lang.Object ref = currentTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return The bytes for currentTo.
       */
      public com.google.protobuf.ByteString
          getCurrentToBytes() {
        java.lang.Object ref = currentTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTo() {
        
        currentTo_ = getDefaultInstance().getCurrentTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The bytes for currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentTo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currentMsg_ = "";
      /**
       * <code>string currentMsg = 3;</code>
       * @return The currentMsg.
       */
      public java.lang.String getCurrentMsg() {
        java.lang.Object ref = currentMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @return The bytes for currentMsg.
       */
      public com.google.protobuf.ByteString
          getCurrentMsgBytes() {
        java.lang.Object ref = currentMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @param value The currentMsg to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentMsg() {
        
        currentMsg_ = getDefaultInstance().getCurrentMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string currentMsg = 3;</code>
       * @param value The bytes for currentMsg to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageRespense)
    }

    // @@protoc_insertion_point(class_scope:MessageRespense)
    private static final ma.enset.stub.Chat.MessageRespense DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.enset.stub.Chat.MessageRespense();
    }

    public static ma.enset.stub.Chat.MessageRespense getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageRespense>
        PARSER = new com.google.protobuf.AbstractParser<MessageRespense>() {
      @java.lang.Override
      public MessageRespense parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageRespense(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageRespense> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageRespense> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.enset.stub.Chat.MessageRespense getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRespense_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageRespense_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\"L\n\016MessageRequest\022\023\n\013curren" +
      "tFrom\030\001 \001(\t\022\021\n\tcurrentTo\030\002 \001(\t\022\022\n\ncurren" +
      "tMsg\030\003 \001(\t\"M\n\017MessageRespense\022\023\n\013current" +
      "From\030\001 \001(\t\022\021\n\tcurrentTo\030\002 \001(\t\022\022\n\ncurrent" +
      "Msg\030\003 \001(\t2F\n\016AppChatService\0224\n\013sendMessa" +
      "ge\022\017.MessageRequest\032\020.MessageRespense(\0010" +
      "\001B\017\n\rma.enset.stubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRequest_descriptor,
        new java.lang.String[] { "CurrentFrom", "CurrentTo", "CurrentMsg", });
    internal_static_MessageRespense_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageRespense_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageRespense_descriptor,
        new java.lang.String[] { "CurrentFrom", "CurrentTo", "CurrentMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
